# Copyright 2016 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

task :default do
	puts "make default"
end

# 生成图标
task :logo do
  Dir.chdir '.' do
    sh 'convert -resize 29x29 logo@1024x1024.png   ./output/icon@29x29.png'
	sh 'convert -resize 40x40 logo@1024x1024.png   ./output/icon@40x40.png'
	sh 'convert -resize 60x60 logo@1024x1024.png   ./output/icon@60x60.png'

	sh 'convert -resize 58x58 logo@1024x1024.png   ./output/icon@29x29@2x.png'
	sh 'convert -resize 80x80 logo@1024x1024.png   ./output/icon@40x40@2x.png'
	sh 'convert -resize 120x120 logo@1024x1024.png ./output/icon@60x60@2x.png'

	sh 'convert -resize 87x87 logo@1024x1024.png   ./output/icon@29x29@3x.png'
	sh 'convert -resize 120x120 logo@1024x1024.png ./output/icon@40x40@3x.png'
	sh 'convert -resize 180x180 logo@1024x1024.png ./output/icon@60x60@3x.png'

	sh 'convert -resize 76x76   logo@1024x1024.png ./output/icon@76x76.png'
	sh 'convert -resize 152x152 logo@1024x1024.png ./output/icon@76x76@2x.png'
	sh 'convert -resize 167x167 logo@1024x1024.png ./output/icon@83x83@2x.png'

  end
end

#
# 生成预览图
# 6sp: 1242x2208
# 6s: 750x1334
# 5s: 640x1136
# 4s: 640x960
#
# 6sp/6s/5s 的长宽比例一样
#
task :screenshots do
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 750x1334! yjyy-iphone6sp-1.png yjyy-iphone6s-1.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-2.png yjyy-iphone6s-2.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-3.png yjyy-iphone6s-3.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-4.png yjyy-iphone6s-4.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-5.png yjyy-iphone6s-5.png'
  end
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 640x1136! yjyy-iphone6sp-1.png yjyy-iphone5s-1.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-2.png yjyy-iphone5s-2.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-3.png yjyy-iphone5s-3.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-4.png yjyy-iphone5s-4.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-5.png yjyy-iphone5s-5.png'
  end
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 640x960! yjyy-iphone6sp-1.png yjyy-iphone4s-1.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-2.png yjyy-iphone4s-2.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-3.png yjyy-iphone4s-3.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-4.png yjyy-iphone4s-4.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-5.png yjyy-iphone4s-5.png'
  end
end

# 合并3张预览图
task :screenshot_small do
  Dir.chdir './misc/screenshots' do
    sh 'convert yjyy-iphone4s-1.png yjyy-iphone4s-3.png yjyy-iphone4s-5.png +append yjyy-ios.png'
	sh 'convert -resize x512 yjyy-ios.png yjyy-ios.png'
	sh 'convert xc:gray      yjyy-ios.png yjyy-ios.png'

	sh 'rm yjyy-ios-0.png' do "ignore error" end
	sh 'rm yjyy-ios-1.png' do "ignore error" end
  end
end
