# Copyright 2016 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# 启动不同版本的模拟器
# rake target=5.1
# rake target=8.4 device_name="iPad 2"

$LOAD_PATH.unshift('/Library/RubyMotion/lib')
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

# 配置信息
$myAppName = "yjyy"

$myAppCodesignCertDeveloper = "iPhone Developer: xxx@xxx.com (xxxxxxxxxx)"
$myAppProfileDeveloper = "#{$myAppName}-debug.mobileprovision"

$myAppCodesignCertDistribution = "iPhone Distribution: xxx@xxx.com (xxxxxxxxxx)"
$myAppProfileDistribution = "#{$myAppName}-release.mobileprovision"

# 加载可选的配置信息
if File.exists? "#{File.dirname(__FILE__)}/_config.rb" then
  load("#{File.dirname(__FILE__)}/_config.rb")
end

# 初始化工程信息
Motion::Project::App.setup do |app|

  # 图标
  app.icons << 'icon.png'

  # 版本
  app.version = "1.1.0"

  # 简体中文
  app.info_plist['CFBundleDevelopmentRegion'] = 'zh_CN'

  # 显示名称
  app.info_plist['CFBundleName'] = '野鸡医院'
  app.info_plist['CFBundleDisplayName'] = '野鸡医院'

  # 账号相关信息从配置文件加载
  # 开发版和发布版本的证书不同
  app.development do
    puts 'build development ...'

    app.name = $myAppName
    app.identifier = $myAppName

    app.codesign_certificate = $myAppCodesignCertDeveloper
    app.provisioning_profile = $myAppProfileDeveloper
  end
  app.release do
    puts 'build release ...'

    app.name = $myAppName
    app.identifier = $myAppName

    app.codesign_certificate = $myAppCodesignCertDistribution
    app.provisioning_profile = $myAppProfileDistribution
  end

  # 依赖的第三方c静态库
  # 被引用的c函数会被编译和链接, 函数的接口在头文件中定义
  app.vendor_project('vendor/gopkg', :static, products: ['libgo.a'], source_files: ['libgo.h'])
end

# rake devide 安装时认证错误, 暂时采用 ios-deploy 安装
# npm install -g ios-deploy
task mydevide: [:"build:device"] do
  sh "ios-deploy --bundle #{File.dirname(__FILE__)}/build/iPhoneOS-9.3-Development/#{MY_APP_NAME}.app"
end

# 生成Go扩展包
task :gopkg do
  Dir.chdir './vendor/gopkg' do
    sh './build.sh'
  end
end

# 格式化代码
task :fmt do
  Dir.chdir './app' do
    sh 'rubocop -a' do |ok, res|
      # 忽略错误
    end
  end
  Dir.chdir './spec' do
    sh 'rubocop -a' do |ok, res|
      # 忽略错误
    end
  end
  Dir.chdir './vendor/gopkg' do
    sh 'go fmt ./...'
  end
  puts 'Done'
end

# 生成图标
task :logo do
  Dir.chdir './misc' do
    sh 'convert -resize 120x120 logo.png icon.png'
    sh 'convert -resize 1024x1024 -alpha off logo.png logo@1024x1024.png'
  end
end

# 生成图标
# 6sp: 1242x2208
# 6s: 750x1334
# 5s: 640x1136
# 4s: 640x960
task :screenshots do
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 750x1334! yjyy-iphone6sp-1.png yjyy-iphone6s-1.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-2.png yjyy-iphone6s-2.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-3.png yjyy-iphone6s-3.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-4.png yjyy-iphone6s-4.png'
    sh 'convert -resize 750x1334! yjyy-iphone6sp-5.png yjyy-iphone6s-5.png'
  end
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 640x1136! yjyy-iphone6sp-1.png yjyy-iphone5s-1.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-2.png yjyy-iphone5s-2.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-3.png yjyy-iphone5s-3.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-4.png yjyy-iphone5s-4.png'
    sh 'convert -resize 640x1136! yjyy-iphone6sp-5.png yjyy-iphone5s-5.png'
  end
  Dir.chdir './misc/screenshots' do
    sh 'convert -resize 640x960! yjyy-iphone6sp-1.png yjyy-iphone4s-1.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-2.png yjyy-iphone4s-2.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-3.png yjyy-iphone4s-3.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-4.png yjyy-iphone4s-4.png'
    sh 'convert -resize 640x960! yjyy-iphone6sp-5.png yjyy-iphone4s-5.png'
  end
end

task :screenshot_small do
  Dir.chdir './misc/screenshots' do
    sh 'convert yjyy-iphone4s-1.png yjyy-iphone4s-3.png yjyy-iphone4s-5.png +append yjyy-ios.png'
	sh 'convert -resize x512 yjyy-ios.png yjyy-ios.png'
	sh 'convert xc:gray      yjyy-ios.png yjyy-ios.png'

	sh 'rm yjyy-ios-0.png' do "ignore error" end
	sh 'rm yjyy-ios-1.png' do "ignore error" end
  end
end
