# Copyright 2016 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ios_application(
   name = "yjyy-swift",
   binary = "yjyy-bin",
   infoplist = "Info.plist",

)

objc_binary(
    name = "yjyy-bin",
    srcs = [
        "MyAppDelegate.swift",
		"MyRootController.swift",
    ],
	asset_catalogs = [
		"Assets.xcassets",
	],
	#app_strings = [
 	#   "Base.lproj",
    #],
)
