# Copyright 2016 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# 设备尺寸
# https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html

task :default do
	puts "make default"
end

task :"yjyy-bin" do
	sh "bazel build //:yjyy-bin --xcode_version=7.3 --ios_sdk_version=9.3"
end

# 生成Go扩展包
task :gopkg do
	Dir.chdir "./vendor/gopkg" do
		sh './build.sh'
	end
end

task :clean do
	sh "bazel clean"
end

task :logo do
  Dir.chdir './misc' do
    sh 'convert -resize 29x29 logo@1024x1024.png icon@29x29.png'
	sh 'convert -resize 40x40 logo@1024x1024.png icon@40x40.png'
	sh 'convert -resize 60x60 logo@1024x1024.png icon@60x60.png'

	sh 'convert -resize 58x58 logo@1024x1024.png icon@29x29@2x.png'
	sh 'convert -resize 80x80 logo@1024x1024.png icon@40x40@2x.png'
	sh 'convert -resize 120x120 logo@1024x1024.png icon@60x60@2x.png'

	sh 'convert -resize 87x87 logo@1024x1024.png icon@29x29@3x.png'
	sh 'convert -resize 120x120 logo@1024x1024.png icon@40x40@3x.png'
	sh 'convert -resize 180x180 logo@1024x1024.png icon@60x60@3x.png'

	sh 'convert -resize 76x76   logo@1024x1024.png icon@76x76.png'
	sh 'convert -resize 152x152 logo@1024x1024.png icon@76x76@2x.png'
	sh 'convert -resize 167x167 logo@1024x1024.png icon@83x83@2x.png'

  end
end

task :screenshot do
	Dir.chdir './misc' do
		sh 'convert -resize 320x480! Default-568h@2x.png Default@1x.png'
		sh 'convert -resize 640x960! Default-568h@2x.png Default@2x.png'
		sh 'convert -resize 1536x2048! Default-736h@3x.png Default@ipad@1536x2048.png'
	end
end
